host=mysql
port=3306
user=maxwell
password=maxwell

producer=kafka
kafka.bootstrap.servers=kafka:9092
kafka_topic=cdc.incremental.binlog

client_id=cdc-warehouse-maxwell
output_binlog_position=true
output_thread_id=true
output_schema_id=true
output_nulls=true
output_ddl=true
bootstrapper=sync

filter=exclude: *.*, include: basiccomment.avatar_commentbatchsource, include: trade.order_info, include: user.user_info
